#ifndef SENSOR_MODULE_H
#define SENSOR_MODULE_H

#include "ip_param_manager.h"
#include "module_ids.h"

#ifdef __cplusplus
extern "C" {
#endif

enum {
    SENSOR_IP_EXPOSURE   = 0,
    SENSOR_IP_GAIN       = 1,
    SENSOR_IP_FPS        = 2,
    SENSOR_IP_RESOLUTION = 3,
    SENSOR_IP_SHUTDOWN   = 4,
    SENSOR_IP_ROI_X      = 5,
    SENSOR_IP_FRAME_CNT  = 6,
    SENSOR_IP_CUR_LUMA   = 7,
};

#define PID_IP_SENSOR_EXPOSURE    MAKE_PARAM_ID(IP_SENSOR, SENSOR_IP_EXPOSURE)
#define PID_IP_SENSOR_GAIN        MAKE_PARAM_ID(IP_SENSOR, SENSOR_IP_GAIN)
#define PID_IP_SENSOR_FPS         MAKE_PARAM_ID(IP_SENSOR, SENSOR_IP_FPS)
#define PID_IP_SENSOR_RESOLUTION  MAKE_PARAM_ID(IP_SENSOR, SENSOR_IP_RESOLUTION)
#define PID_IP_SENSOR_SHUTDOWN    MAKE_PARAM_ID(IP_SENSOR, SENSOR_IP_SHUTDOWN)
#define PID_IP_SENSOR_ROI_X       MAKE_PARAM_ID(IP_SENSOR, SENSOR_IP_ROI_X)
#define PID_IP_SENSOR_FRAME_CNT   MAKE_PARAM_ID(IP_SENSOR, SENSOR_IP_FRAME_CNT)
#define PID_IP_SENSOR_CUR_LUMA    MAKE_PARAM_ID(IP_SENSOR, SENSOR_IP_CUR_LUMA)

#define CMD_SENSOR_SHUTDOWN      PID_IP_SENSOR_SHUTDOWN

void sensor_module_init(void);

#ifdef __cplusplus
}
#endif

#endif /* SENSOR_MODULE_H */
